server:
  port: 8001

#Этот конфиг можно не описывать, если приложение и RabbitMQ запускаются на локальной машине.
#Иначе надо прописывать.
#Сделано на будущее
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: klozevitz
    password: ItsMyLife29101012
  datasource:
    url: jdbc:postgresql://localhost:6543/tg_bot_test
    username: klozevitz
    password: ItsMyLife29101012
  jpa:
    generate-ddl: true
#

fileService:
  token: 7268790759:AAGWm_KF-JJHrK2Y1bW-9bNh3C2FL9A38_g
  service:
    file_info:
      url: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
    file_storage:
      url: https://api.telegram.org/file/bot{token}/{filePath}

link:
  address: 127.0.0.1:8003

salt: Pdlkfsj4l5k2Y324kjFj23kAlj234sdfkUlk5Padas6898s

#debug: true