server:
  port: 8001

#Этот конфиг можно не описывать, если приложение и RabbitMQ запускаются на локальной машине.
#Иначе надо прописывать.
#Сделано на будущее
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: klozevitz
    password: ItsMyLife29101012
  datasource:
    url: jdbc:postgresql://localhost:6543/tg_bot_test
    username: klozevitz
    password: ItsMyLife29101012
  jpa:
    generate-ddl: true
#

#debug: true