server:
  port: 8003

# We are not to specify this config block if we are going to run RabbitMQ on the local machine.
# We are to do this if we are not.
# done in advance

spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/tg_bot_test
    username: klozevitz
    password: ItsMyLife29101012
  jpa:
    generate-ddl: true
#

# for hash function
salt: Pdlkfsj4l5k2Y324kjFj23kAlj234sdfkUlk5Padas6898s

#debug: true