server:
  port: 8003

#Этот конфиг можно не описывать, если приложение и RabbitMQ запускаются на локальной машине.
#Иначе надо прописывать.
#Сделано на будущее
spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/tg_bot_test
    username: klozevitz
    password: ItsMyLife29101012
  jpa:
    generate-ddl: true
#

salt: Pdlkfsj4l5k2Y324kjFj23kAlj234sdfkUlk5Padas6898s

#debug: true